import type { LocaleCode } from './build-context';

const copy = {
  en: {
    heroFocus: 'Product · Systems · Platforms',
    heroLineStarts: [0, 5, 7],
    recordTitle: 'My work',
    recordUpdated: 'Updated',
    layers: ['Interface', 'Product', 'Systems', 'Infrastructure'],
    layerDescriptions: [
      'Interaction, accessibility, and visual systems.',
      'Journeys, constraints, and useful product behavior.',
      'Services, data paths, boundaries, and reliability.',
      'Delivery, automation, environments, and operations.'
    ],
    scrollPrompt: 'Scroll through the system',
    workKicker: 'Projects',
    workTitle: "Projects I've worked on.",
    workAcrossLayers: 'Products, platforms & tools',
    projectLayers: 'Engineering scope',
    roleLabel: 'My role',
    projectWorkTitle: 'Recorded activity mix',
    ownerWorkTitle: 'My contribution',
    ownerWorkSource: 'My estimate.',
    coreStackLabel: 'Core stack',
    moreTechnologies: (count: number) => `${count} more technologies in project details`,
    landscapeKicker: 'What I work on',
    landscapeTitle: 'Interfaces, APIs, and what connects them.',
    landscapeDescription: 'Frontend, backend, AI, and delivery: where each fits into my projects.',
    landscapeList: 'Engineering landscape relationships',
    mixTitle: 'Recorded activity mix',
    mixNote: "Based on the activities I've recorded, not hours worked. Each activity counts once, split across its areas.",
    mixSample: (count: number) => `${count} recorded ${count === 1 ? 'activity' : 'activities'}.`,
    domainLabels: {
      frontend: 'Frontend', backend: 'Backend', devops: 'DevOps', infrastructure: 'Infrastructure',
      data: 'Data', 'ai-ml': 'AI / ML', mobile: 'Mobile', desktop: 'Desktop', embedded: 'Embedded',
      'quality-engineering': 'Quality engineering', security: 'Security',
      'developer-experience': 'Developer experience', 'product-design': 'Product design', other: 'Other'
    },
    experienceKicker: 'Experience',
    experienceTitle: "Where I've worked.",
    recommendationsKicker: 'Recommendations',
    recommendationsTitle: "People I've worked with.",
    recommendationsIntro: 'Their words, from our time working together.',
    recommendationsSource: 'Read the full recommendations on LinkedIn',
    recommendationsTranslation: 'Translated from English. The original recommendations are on LinkedIn.',
    contactKicker: 'Contact',
    contactTitle: "Let's talk.",
    contactIntro: 'Have a project in mind, or want to work together? You can reach me here.',
    contactEmail: 'Email',
    contactPhone: 'Phone',
    contactSocials: 'Find me online',
    contactAction: 'Get in touch',
    principlesKicker: 'My approach',
    principlesTitle: 'How I work.',
    toolboxKicker: 'Toolbox',
    toolboxTitle: 'What I build with.',
    noExperience: "I'm adding more about my experience here.",
    inspectProject: 'Open project',
    previewLabel: 'Project visual preview',
    projectStackLabel: 'Project technologies and AI',
    aiTag: 'AI',
    diagramLabel: 'Abstract system diagram',
    sectionNavigation: 'Page sections',
    sections: ['Intro', 'Work', 'Landscape', 'Experience', 'About'],
    architectureLabel: 'Architecture layers from interface to infrastructure',
    ribbonLead: 'System layers',
    details: 'Technical detail',
    allProjects: 'All projects'
  },
  'pt-BR': {
    heroFocus: 'Produto · Sistemas · Plataformas',
    heroLineStarts: [0, 4, 6],
    recordTitle: 'Meu trabalho',
    recordUpdated: 'Atualizado',
    layers: ['Interface', 'Produto', 'Sistemas', 'Infraestrutura'],
    layerDescriptions: [
      'Interação, acessibilidade e sistemas visuais.',
      'Jornadas, restrições e comportamento útil de produto.',
      'Serviços, caminhos de dados, limites e confiabilidade.',
      'Entrega, automação, ambientes e operações.'
    ],
    scrollPrompt: 'Percorra as camadas do sistema',
    workKicker: 'Projetos',
    workTitle: 'Projetos em que trabalhei.',
    workAcrossLayers: 'Produtos, plataformas e ferramentas',
    projectLayers: 'Áreas de atuação',
    roleLabel: 'Minha atuação',
    projectWorkTitle: 'Distribuição das atividades registradas',
    ownerWorkTitle: 'Minha atuação',
    ownerWorkSource: 'Minha estimativa.',
    coreStackLabel: 'Stack principal',
    moreTechnologies: (count: number) => `Mais ${count} tecnologias nos detalhes do projeto`,
    landscapeKicker: 'Minhas áreas de atuação',
    landscapeTitle: 'Interfaces, APIs e o que conecta tudo isso.',
    landscapeDescription: 'Frontend, backend, IA e entrega: onde cada área entra nos meus projetos.',
    landscapeList: 'Relações do panorama de engenharia',
    mixTitle: 'Distribuição das atividades registradas',
    mixNote: 'Com base nas atividades que registrei, não em horas trabalhadas. Cada atividade conta uma vez, dividida entre suas áreas.',
    mixSample: (count: number) => `${count} ${count === 1 ? 'atividade registrada' : 'atividades registradas'}.`,
    domainLabels: {
      frontend: 'Frontend', backend: 'Backend', devops: 'DevOps', infrastructure: 'Infraestrutura',
      data: 'Dados', 'ai-ml': 'IA / ML', mobile: 'Mobile', desktop: 'Desktop', embedded: 'Embarcados',
      'quality-engineering': 'Engenharia de qualidade', security: 'Segurança',
      'developer-experience': 'Experiência de desenvolvimento', 'product-design': 'Design de produto', other: 'Outros'
    },
    experienceKicker: 'Experiência',
    experienceTitle: 'Por onde passei.',
    recommendationsKicker: 'Recomendações',
    recommendationsTitle: 'O que falam sobre mim.',
    recommendationsIntro: 'Palavras de quem trabalhou comigo.',
    recommendationsSource: 'Ler as recomendações completas no LinkedIn',
    recommendationsTranslation: 'Traduções do inglês. Os textos originais estão no LinkedIn.',
    contactKicker: 'Contato',
    contactTitle: 'Vamos conversar.',
    contactIntro: 'Tem um projeto em mente ou quer trabalhar comigo? É só me chamar.',
    contactEmail: 'E-mail',
    contactPhone: 'Telefone',
    contactSocials: 'Minhas redes',
    contactAction: 'Fale comigo',
    principlesKicker: 'Meu jeito de trabalhar',
    principlesTitle: 'Como eu trabalho.',
    toolboxKicker: 'Ferramentas',
    toolboxTitle: 'Tecnologias que uso.',
    noExperience: 'Estou adicionando mais sobre minha experiência aqui.',
    inspectProject: 'Abrir projeto',
    previewLabel: 'Prévia visual do projeto',
    projectStackLabel: 'Tecnologias e IA do projeto',
    aiTag: 'IA',
    diagramLabel: 'Diagrama abstrato de sistema',
    sectionNavigation: 'Seções da página',
    sections: ['Introdução', 'Trabalhos', 'Panorama', 'Experiência', 'Sobre'],
    architectureLabel: 'Camadas de arquitetura da interface à infraestrutura',
    ribbonLead: 'Camadas do sistema',
    details: 'Detalhe técnico',
    allProjects: 'Todos os projetos'
  }
} as const;

export function portfolioCopy(locale: LocaleCode) {
  return copy[locale];
}
